version: '3.3'

services:

  web:
    build:
      context: src

    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "80:8080"

    volumes:
      - ./src:/usr/src
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: src
    command: celery --app worker.celery worker --loglevel=info

    volumes:
      - ./src:/usr/src
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
